services:
  alignme_nginx:
    container_name: alignme_nginx
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/templates:/etc/nginx/templates
    ports:
      - "80:80"
    depends_on:
      - alignme_server
    networks:
      - alignme-network
  alignme_server:
    container_name: alignme-server
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    env_file:
      - ./src/configs/.env.development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn run start:dev
    ports:
      - "4000:4000"
    depends_on:
      - alignme_db
    networks:
      - alignme-network

  alignme_db:
    container_name: alignme_db
    image: postgres:15
    env_file:
      - ./src/configs/.env.development
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - alignme-network

networks:
  alignme-network:
    driver: bridge